### ISSUE TITLE
Java dependency issues since 0.46

### ISSUE THREAD

**Issue by zemiak** [jbangdev/homebrew-tap#3]
Hello,

the Java dependency makes the upgrade from 0.45 to 0.47.1 impossible:
** depends_on :java => "1.8+"**

This causes:
**Install AdoptOpenJDK with Homebrew Cask:
  brew cask install adoptopenjdk
Error: jbang: An unsatisfied requirement failed this build.
**

java -version
**openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
**

I have downloaded OpenJDK from adoptopenjdk site directly and installed it via DMG. Java1.8 as well.

Please, revert the dependecy or fix

Thanks,
Miro

**Comment by maxandersen** [comment]
I'm confused when you are getting the error ? We removed the Java dependency as jbang now will install it when needed.

**Comment by zemiak** [comment]
Yes, I am confused as well. The problem, it turned out, was a jdk-12.0.1.jdk, that was installed along my JVMs.
Sorry for misleading you 🤷‍♂️

**Comment by maxandersen** [comment]
Okey - still worrisome you are getting such errors related to jbang. Jbang should work with any jdk 8 and above. 
Feel free to reopen if turns out jbang had some issue it shouldn't have with brew jdk Install.
